- name: backend server configuration
  hosts: backend
  become: yes
  tasks:
    - name: disble the nodejs version
      ansible.builtin.command: 
        cmd: dnf module disble nodejs -y
        
    - name: enable the nodejs 20 version
      ansible.builtin.shell: "{{ items }}"
      with_items:
        - dnf module enable nodejs:20 -y 

    - name: install the node js package
      ansible.builtin.package:
        name: 
        - nodejs
        state: present