- name: mysql server creation
  hosts: mysql
  become: yes
  tasks:  
    - name: the sql server installation
      ansible.builtin.package:
        name: mysql-server
        state: present
        
    - name: mysql-server servicestart
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true